# Generated by Django 4.1.5 on 2023-01-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_project_alter_todo_status_alter_todo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Waiting'), (2, 'InProgress'), (3, 'Done'), (4, 'Closed')], verbose_name='status'),
        ),
        migrations.DeleteModel(
            name='TodoStatus',
        ),
    ]
